# Generated by Django 4.1.5 on 2023-03-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('jobtype', models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=15)),
            ],
        ),
    ]
