# Generated by Django 4.1.5 on 2023-03-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobtype',
            new_name='job_type',
        ),
        migrations.AddField(
            model_name='job',
            name='descrition',
            field=models.TextField(default='descrition', max_length=1000),
        ),
        migrations.AddField(
            model_name='job',
            name='experiance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1),
        ),
    ]
